# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.post = QtWidgets.QFrame(self.centralwidget)
        self.post.setGeometry(QtCore.QRect(10, 340, 1261, 421))
        self.post.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.post.setFrameShadow(QtWidgets.QFrame.Raised)
        self.post.setObjectName("post")
        self.listOfVideos = QtWidgets.QFrame(self.post)
        self.listOfVideos.setGeometry(QtCore.QRect(10, 10, 251, 401))
        self.listOfVideos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listOfVideos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.listOfVideos.setObjectName("listOfVideos")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.listOfVideos)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 231, 381))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.videoList = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.videoList.setFrameShape(QtWidgets.QFrame.HLine)
        self.videoList.setFrameShadow(QtWidgets.QFrame.Plain)
        self.videoList.setObjectName("videoList")
        self.verticalLayout_6.addWidget(self.videoList)
        self.setDirectoryButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.setDirectoryButton.setObjectName("setDirectoryButton")
        self.verticalLayout_6.addWidget(self.setDirectoryButton)
        self.plot_2 = QtWidgets.QFrame(self.post)
        self.plot_2.setGeometry(QtCore.QRect(730, 10, 521, 401))
        self.plot_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plot_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_2.setObjectName("plot_2")
        self.heartbeatPlot = QtWidgets.QWidget(self.plot_2)
        self.heartbeatPlot.setGeometry(QtCore.QRect(10, 10, 501, 381))
        self.heartbeatPlot.setObjectName("heartbeatPlot")
        self.frame = QtWidgets.QFrame(self.post)
        self.frame.setGeometry(QtCore.QRect(270, 10, 451, 401))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 431, 381))
        self.widget.setObjectName("widget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_7.addWidget(self.checkBox_3, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_7.addWidget(self.checkBox_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_8.addWidget(self.checkBox_5, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_6 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_8.addWidget(self.checkBox_6, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_6.addWidget(self.checkBox_2, 0, QtCore.Qt.AlignHCenter)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_6.addWidget(self.checkBox, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.runAnalysis = QtWidgets.QPushButton(self.widget)
        self.runAnalysis.setObjectName("runAnalysis")
        self.verticalLayout_10.addWidget(self.runAnalysis)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_10.addWidget(self.progressBar, 0, QtCore.Qt.AlignTop)
        self.pre = QtWidgets.QFrame(self.centralwidget)
        self.pre.setGeometry(QtCore.QRect(10, 10, 1261, 321))
        self.pre.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pre.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pre.setObjectName("pre")
        self.stimulus = QtWidgets.QFrame(self.pre)
        self.stimulus.setGeometry(QtCore.QRect(10, 10, 441, 301))
        self.stimulus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stimulus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stimulus.setObjectName("stimulus")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.stimulus)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 421, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stimulusTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.stimulusTitle.setMaximumSize(QtCore.QSize(53, 16))
        self.stimulusTitle.setObjectName("stimulusTitle")
        self.horizontalLayout_5.addWidget(self.stimulusTitle)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.preSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.preSpinBox.setObjectName("preSpinBox")
        self.horizontalLayout_4.addWidget(self.preSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.stimSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.stimSpinBox.setObjectName("stimSpinBox")
        self.horizontalLayout_3.addWidget(self.stimSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.interSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.interSpinBox.setObjectName("interSpinBox")
        self.horizontalLayout.addWidget(self.interSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.numberSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.numberSpinBox.setObjectName("numberSpinBox")
        self.horizontalLayout_2.addWidget(self.numberSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.plotButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.plotButton.setObjectName("plotButton")
        self.verticalLayout.addWidget(self.plotButton)
        self.plot = QtWidgets.QFrame(self.pre)
        self.plot.setGeometry(QtCore.QRect(460, 10, 521, 301))
        self.plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot.setObjectName("plot")
        self.stimulusPlot = QtWidgets.QWidget(self.plot)
        self.stimulusPlot.setGeometry(QtCore.QRect(10, 10, 501, 281))
        self.stimulusPlot.setObjectName("stimulusPlot")
        self.run = QtWidgets.QFrame(self.pre)
        self.run.setGeometry(QtCore.QRect(990, 10, 261, 301))
        self.run.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.run.setFrameShadow(QtWidgets.QFrame.Raised)
        self.run.setObjectName("run")
        self.widget1 = QtWidgets.QWidget(self.run)
        self.widget1.setGeometry(QtCore.QRect(9, 9, 241, 281))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setMaximumSize(QtCore.QSize(36, 16))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget1)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_7.addWidget(self.plainTextEdit, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.runButton = QtWidgets.QPushButton(self.widget1)
        self.runButton.setMinimumSize(QtCore.QSize(66, 32))
        self.runButton.setObjectName("runButton")
        self.verticalLayout_8.addWidget(self.runButton)
        self.cancelButton = QtWidgets.QPushButton(self.widget1)
        self.cancelButton.setObjectName("cancelButton")
        self.verticalLayout_8.addWidget(self.cancelButton)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Frequency Detector"))
        self.label_6.setText(_translate("MainWindow", "Pick a video to analyze"))
        self.setDirectoryButton.setText(_translate("MainWindow", "Set Directory..."))
        self.label_7.setText(_translate("MainWindow", "Options"))
        self.checkBox_3.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_4.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_5.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_6.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_2.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.runAnalysis.setText(_translate("MainWindow", "Run Analysis"))
        self.label_8.setText(_translate("MainWindow", "Analysis progress"))
        self.stimulusTitle.setText(_translate("MainWindow", "Stimulus"))
        self.label.setText(_translate("MainWindow", "Pre stimulus (s)"))
        self.label_2.setText(_translate("MainWindow", "Stimulus (s)"))
        self.label_3.setText(_translate("MainWindow", "Interval (s)"))
        self.label_4.setText(_translate("MainWindow", "No. stimulus"))
        self.plotButton.setText(_translate("MainWindow", "Plot Stimuli"))
        self.label_5.setText(_translate("MainWindow", "Notes"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
