# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'postExperimentGUI.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 751)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.postExperimentFrame = QtWidgets.QFrame(self.centralwidget)
        self.postExperimentFrame.setGeometry(QtCore.QRect(10, 10, 1421, 511))
        self.postExperimentFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.postExperimentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.postExperimentFrame.setLineWidth(2)
        self.postExperimentFrame.setObjectName("postExperimentFrame")
        self.pickAVideoFrame = QtWidgets.QFrame(self.postExperimentFrame)
        self.pickAVideoFrame.setGeometry(QtCore.QRect(10, 10, 251, 491))
        self.pickAVideoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pickAVideoFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pickAVideoFrame.setObjectName("pickAVideoFrame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.pickAVideoFrame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 231, 471))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pickAVideoLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.pickAVideoLabel.setObjectName("pickAVideoLabel")
        self.verticalLayout_6.addWidget(self.pickAVideoLabel, 0, QtCore.Qt.AlignHCenter)
        self.videoList = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.videoList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.videoList.setObjectName("videoList")
        self.verticalLayout_6.addWidget(self.videoList)
        self.setInputDirectoryButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.setInputDirectoryButton.setObjectName("setInputDirectoryButton")
        self.verticalLayout_6.addWidget(self.setInputDirectoryButton)
        self.videoPreviewFrame = QtWidgets.QFrame(self.postExperimentFrame)
        self.videoPreviewFrame.setGeometry(QtCore.QRect(730, 10, 681, 491))
        self.videoPreviewFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.videoPreviewFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.videoPreviewFrame.setObjectName("videoPreviewFrame")
        self.videoWidget = VideoPlayer(self.videoPreviewFrame)
        self.videoWidget.setGeometry(QtCore.QRect(0, 0, 671, 471))
        self.videoWidget.setMaximumSize(QtCore.QSize(680, 471))
        self.videoWidget.setObjectName("videoWidget")
        self.optionsFrame = QtWidgets.QFrame(self.postExperimentFrame)
        self.optionsFrame.setGeometry(QtCore.QRect(270, 10, 451, 491))
        self.optionsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.optionsFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.optionsFrame.setObjectName("optionsFrame")
        self.layoutWidget = QtWidgets.QWidget(self.optionsFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 431, 471))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.OptionsLabel = QtWidgets.QLabel(self.layoutWidget)
        self.OptionsLabel.setObjectName("OptionsLabel")
        self.verticalLayout_16.addWidget(self.OptionsLabel, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.verticalLayout_16)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectRoiButton = QtWidgets.QPushButton(self.layoutWidget)
        self.selectRoiButton.setObjectName("selectRoiButton")
        self.horizontalLayout.addWidget(self.selectRoiButton)
        self.cropVideoButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cropVideoButton.setObjectName("cropVideoButton")
        self.horizontalLayout.addWidget(self.cropVideoButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_7.addWidget(self.checkBox_3, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_7.addWidget(self.checkBox_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_8.addWidget(self.checkBox_5, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_8.addWidget(self.checkBox_6, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_6.addWidget(self.checkBox_2, 0, QtCore.Qt.AlignHCenter)
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_6.addWidget(self.checkBox, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.runAnalysisButton = QtWidgets.QPushButton(self.layoutWidget)
        self.runAnalysisButton.setObjectName("runAnalysisButton")
        self.verticalLayout_15.addWidget(self.runAnalysisButton)
        self.updateFrequencyPlotButton = QtWidgets.QPushButton(self.layoutWidget)
        self.updateFrequencyPlotButton.setFlat(False)
        self.updateFrequencyPlotButton.setObjectName("updateFrequencyPlotButton")
        self.verticalLayout_15.addWidget(self.updateFrequencyPlotButton)
        self.verticalLayout_10.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.progressLabel = QtWidgets.QLabel(self.layoutWidget)
        self.progressLabel.setText("")
        self.progressLabel.setObjectName("progressLabel")
        self.verticalLayout_14.addWidget(self.progressLabel, 0, QtCore.Qt.AlignHCenter)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_14.addWidget(self.progressBar)
        self.verticalLayout_10.addLayout(self.verticalLayout_14)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 530, 1431, 421))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.frequencyPlot = QtWidgets.QWidget(self.frame_2)
        self.frequencyPlot.setGeometry(QtCore.QRect(10, 10, 591, 401))
        self.frequencyPlot.setObjectName("frequencyPlot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pickAVideoLabel.setText(_translate("MainWindow", "Pick a video to analyze"))
        self.videoList.setSortingEnabled(True)
        self.setInputDirectoryButton.setText(_translate("MainWindow", "Set Directory..."))
        self.OptionsLabel.setText(_translate("MainWindow", "Options"))
        self.selectRoiButton.setText(_translate("MainWindow", "Select ROI"))
        self.cropVideoButton.setText(_translate("MainWindow", "Crop video to ROI"))
        self.checkBox_3.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_4.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_5.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_6.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_2.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.runAnalysisButton.setText(_translate("MainWindow", "Run Analysis"))
        self.updateFrequencyPlotButton.setText(_translate("MainWindow", "Update Plots"))

from PostExperimentClasses.VideoPlayer import VideoPlayer
